#!/bin/bash
setKey(){
   gpg --armour --export $st
   git config --global user.signingkey $st
   [ -f ~/.bashrc ] && echo 'export GPG_TTY=$(tty)' >> ~/.bashrc 
   source ~/.bashrc
}

echo "Hemlo! Press 0 to use an existing gpg key and 1 to create a new key and 2 to terminate the script"
read ch
if [[ $ch -eq 0 ]];
   then 
   key=$(gpg --list-secret-keys --keyid-format=long|awk '/sec/{if (length($2)>0) print $2}')
   uid=$(gpg --list-secret-keys --keyid-format=long|awk '/uid/')
   k=0
   declare -a keys
   declare -a id
   n=${#key}
   n1=${#uid}
   
   for((i=0;i<$n;i++));	
      do
      if [[ ${key:$i:1} == "/" ]]
         then 
         keys[$k]=${key:$i+1:16}
         ((k++))
      fi     
      done
     
     k=0
     a=0
     b=0
     
     for((i=0;i<$n1;i++))
     do
     if [[ ${uid:$i:1} == ']' ]] 
        then
        a=$i+1
     fi
     
     if [[ ${uid:$i:1} == '>' ]]
        then
        b=$i+1
        id[$k]=${uid:$a+1:$b-$a}
        ((k++))
     fi
     done
     
     echo "Please choose a key"
     for((i=0;i<$k;i++));
       do
       in=$((i+1))
       echo $in. ${id[$i]}
       done
       
     read final
     if [[ $final -le $k ]]
        then
        gpg --armor --export ${keys[$((final-1))]}
     
     else
        echo "Wrong Input"
     fi
     
    st=${keys[$final-1]}
    setKey

    elif [[ $ch -eq 1 ]];
         then 
         gpg --full-generate-key
         echo "Paste the secret of the Key generated"
         read x
         st=$x
         setKey
         
    elif [[ $ch -eq 2 ]];
         then
         echo "Automation stopped"
         
    else 
         echo "Invalid choice"
         bash gpg_automater.sh
    fi
